web/user/views.py
# -*- coding: utf-8 -*-
import logging

from flask import Blueprint, redirect, render_template, request, url_for
from flask.ext.login import (current_user, login_required, login_user,
                             logout_user)

from web.extensions import login_manager
from web.user.forms import LoginForm
from web.user.models import User
from web.utils import flash_errors, format_error

logger = logging.getLogger(__name__)

blueprint = Blueprint('user', __name__, url_prefix='/user',
                      static_folder="../static")


@login_manager.user_loader
def load_user(id):
    return User.get_by_id(int(id))


def extra_login_user(user, remember=False, force=False):
    if login_user(user, remember, force):
        current_user.update_lastvisit()


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('commission.consolidated'))

    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            extra_login_user(form.user)
            redirect_url = request.args.get("next") or url_for('public.index')
            return redirect(redirect_url)
        else:
            logger.debug('USER LOGIN')
            logger.debug('Request data: %(data)s' % {'data': request.form})
            logger.debug('Form error: %(error)s' % {'error': format_error(form)})

            flash_errors(form)

    return render_template("user/login.html", form=form)


@blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('public.index'))

web/templates/footer.html
<footer>
  <small>
    <ul class="company">
      <li>&copy; Mobispot. Ltd. All rights reserved</li>
    </ul>
    <ul class="footer-nav">
      <li><a href="mailto:sales@mobispot.com">Contact</a></li>
    </ul>
  </small>
</footer>

web/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" ng-app="term_admin" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" ng-app="term_admin" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" ng-app="term_admin" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" ng-app="term_admin" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}Комиссии по терминалам{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
  {% with form=form  %}
  {% include "nav.html" %}
  {% endwith %}

  <header>{% block header %}{% endblock %}</header>
  <div class="{% block content_class %}container{% endblock content_class %}">

    <div role="main">
      {% block menu %}
        <div class="row">
          <div class="col-md-11">
            {% block breadcrumb %}{% endblock %}
          </div>
        </div>
      {% endblock %}

      {% block content %}{% endblock %}
    </div>

  </div>

  {% include "footer.html" %}
{% endblock %}

{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}

</body>
</html>

web/templates/nav.html
{% set navigation_bar = [
    (url_for('commission.consolidated'), 'consolidated', 'Сводное движение средств '),
    (url_for('commission.history'), 'history', 'По-месячная история'),
] -%}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('public.index') }}">Комиссии по терминалам</a>
    </div>
    {% if 'user' in g and g.user.group == 1 %}
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-left">
        {% for href, id, caption in navigation_bar %}
          {% if request.endpoint %}
            <li {% if id in request.endpoint %} class="active"{% endif %}>
              <a class="navbar-link" href="{{ href|e }}">{{ caption|e }}</a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li>
            <a class="navbar-link" href="{{ url_for('user.logout') }}">Выйти <i class="fa fa-sign-out"></i>
            </a>
          </li>
       </ul>
    </div>
    {% endif %}
  </div>
</nav>